platform :ios,'6.0'
target 'SimpleTravel' do
pod 'AMap2DMap'
pod 'AMapSearch'
pod 'AMapLocation'
pod 'MJRefresh'
pod 'IQKeyboardManager'
pod 'SVProgressHUD'
pod 'FMDB'
pod 'AFNetworking'
pod 'YYImage'
pod 'pop', '~> 1.0'
pod 'YYModel'
pod 'SDWebImage'
end
